name: Update PyPI Downloads

on:
  # Remove the "#" to get the cronjob running at 01:15 UTC
  # schedule:
  #  - cron: '15 3 * * *'  # Every day at 01:15 UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pypistats

      - name: Run download tracker
        run: python track_downloads.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add downloads.json README.md
          git commit -m 'chore: update total downloads' || echo "No changes to commit"
          git push
